### ISSUE TITLE
test doesn't run - chapter 6/database/query_test.go:40

### ISSUE THREAD

**Issue by iateadonut** [PacktPublishing/Go-Programming-Cookbook-Second-Edition#2]
chapter 6/database/query_test.go:40

`if err := Query(tt.args.db); (err != nil) != tt.wantErr {`
should be:
`if err := Query(tt.args.db, "something"); (err != nil) != tt.wantErr {`

**Comment by agtorre** [comment]
Updated, thank you for the report!
